### ISSUE TITLE
Doesn't work when used on nested items

### ISSUE THREAD

**Issue by ivansimplistic** [svivian/sv-hover-intent-js#1]
When I hover a nested item that also has the over event, the onExit event is triggered on the parent. This feature works well on the original jQuery plugin, it allows me to build menus with nested submenus.

**Comment by svivian** [comment]
I added a nested item example to the demo to test this, but it worked fine. I wasn't able to reproduce the problem. If this issue is still relevant, feel free to provide a reduced test case and I'll look into it.
